language: node_js
sudo: false
node_js:
  - 0.10
env:
  - PATH=$HOME/purescript:$PATH
install:
  - npm install bower gulp -g
  - npm install
  - bower install --production
script:
  - gulp make
  - bower install
  - gulp test
